feat(Make): add colcon support for Make
Delete cmake support which is useless for lucy project

Signed-off-by: m-brl <mathieu.borel@epitech.eu>

diff --git a/lucy_utils/Make b/lucy_utils/Make
--- a/lucy_utils/Make
+++ b/lucy_utils/Make
@@ -1,19 +1,9 @@
 #!/bin/bash
 
-display_header() {
-    printf "\033[32m"
-    printf "**************************************************\n"
-    printf "*                                                *\n"
-    printf "*  Build the project                             *\n"
-    printf "*                                                *\n"
-    printf "*  Version: %-36s *\n" $VERSION
-    printf "*                                                *\n"
-    printf "**************************************************\n"
-    printf "\033[0m"
-}
+Header
 
 display_help() {
-    echo "Usage: $0 [options]"
+    echo "Usage: Make [OPTIONS]... [TARGET]"
     echo
     echo "Options:"
     echo "  -h, --help      Show this help message"
@@ -21,55 +11,61 @@ display_help() {
     echo "  -r, --rebuild   Rebuild the project"
     echo "  -c, --clean     Clean the build directory"
     echo "  -j, --jobs      Number of jobs to run simultaneously"
-    echo "  -p, --preset    Specify the preset to use"
-    echo "  --build-dir     Specify the build directory"
     echo "  --now           Skip the delay before cleaning"
 }
 
-clean_build() {
-    if [[ ! -d "$BUILD_DIR" ]]; then
-        echo "Build directory $BUILD_DIR does not exist. Nothing to clean."
-        return
-    fi
+clean() {
+    cd $LUCY
     stopwatch=$DELAY_BEFORE_PURGE
     while [[ $stopwatch -gt 0 ]]; do
         echo -e "Cleaning the build directory in $stopwatch seconds..."
         sleep 1
         ((stopwatch--))
     done
-    echo "Cleaning the build directory..."
-    rm -rf "$BUILD_DIR"
+    rm -r install
+    rm -r build
+    rm -r log
 }
 
-build() {
-    if [[ ! -f "CMakeLists.txt" ]]; then
-        echo "CMakeLists.txt not found. Please run this script from the project root directory."
+#build_cmake() {
+#    if [[ ! -f "CMakeLists.txt" ]]; then
+#        echo "CMakeLists.txt not found. Please run this script from the project root directory."
+#        exit 1
+#    fi
+#    if [[ -z "$PRESET_FLAG" ]]; then
+#        echo -e "\033[33mNo preset defined\033[0m"
+#    fi
+#    if [[ ! -d "$BUILD_DIR" ]]; then
+#        echo -e "\033[32mBuild directory $BUILD_DIR does not exist. Creating it...\033[0m"
+#        mkdir -p $BUILD_DIR
+#    fi
+#    {
+#        cd $BUILD_DIR
+#        $CMAKE $PRESET_FLAG ..
+#        if [[ "$?" -ne 0 ]]; then
+#            echo -e "\033[31mCMake configuration failed.\033[0m"
+#            exit 1
+#        else
+#            echo -e "\033[32mCMake configuration succeeded.\033[0m"
+#        fi
+#        $CMAKE --build . -- -j $JOBS
+#        if [[ "$?" -ne 0 ]]; then
+#            echo -e "\033[31mBuild failed.\033[0m"
+#            exit 1
+#        else
+#            echo -e "\033[32mBuild succeeded.\033[0m"
+#        fi
+#    }
+#}
+
+build_colcon() {
+    cd $LUCY
+    COLCON=$(command -v colcon 2> /dev/null)
+    if [[ -z "$COLCON" ]]; then
+        echo -e "\033[31mcolcon not found. Please install colcon.\033[0m"
         exit 1
     fi
-    if [[ -z "$PRESET_FLAG" ]]; then
-        echo -e "\033[33mNo preset defined\033[0m"
-    fi
-    if [[ ! -d "$BUILD_DIR" ]]; then
-        echo -e "\033[32mBuild directory $BUILD_DIR does not exist. Creating it...\033[0m"
-        mkdir -p $BUILD_DIR
-    fi
-    {
-        cd $BUILD_DIR
-        $CMAKE $PRESET_FLAG ..
-        if [[ "$?" -ne 0 ]]; then
-            echo -e "\033[31mCMake configuration failed.\033[0m"
-            exit 1
-        else
-            echo -e "\033[32mCMake configuration succeeded.\033[0m"
-        fi
-        $CMAKE --build . -- -j $JOBS
-        if [[ "$?" -ne 0 ]]; then
-            echo -e "\033[31mBuild failed.\033[0m"
-            exit 1
-        else
-            echo -e "\033[32mBuild succeeded.\033[0m"
-        fi
-    }
+    $COLCON build --parallel-workers $JOBS
 }
 
 generate_ctags() {
@@ -83,18 +79,16 @@ generate_ctags() {
 
 
 
-
-
 CMAKE=$(command -v cmake 2> /dev/null)
 if [[ $? -ne 0 ]]; then
     echo -e "\033[31mCMake not found. Please install CMake.\033[0m"
     exit 1
 fi
 
-OPTIONS=":hbrcj:p:"
-LONGOPTS="help,build,rebuild,clean,jobs:,preset:,build-dir:,now"
+OPTIONS=":hbrcj:"
+LONGOPTS="help,build,rebuild,clean,jobs:,now"
 OPTS=$(getopt --name "$0" -o $OPTIONS -l $LONGOPTS -- "$@")
-if [ $? -ne 0 ]; then
+if [[ $? -ne 0 ]]; then
     display_help
     exit 1
 fi
@@ -102,15 +96,6 @@ fi
 TARGET="none"
 JOBS=1
 DELAY_BEFORE_PURGE=3
-PRESET_FLAG=""
-BUILD_DIR="build"
-UPLOAD=false
-
-
-
-
-
-display_header
 
 eval set -- "$OPTS"
 
@@ -123,7 +108,7 @@ while true; do
             ;;
         -b|--build)
             if [[ "$TARGET" != "none" ]]; then
-                echo "Multiple targets specified. Please choose only one."
+                echo "\033[31mMultiple targets specified. Please choose only one.\033[0m"
                 exit 1
             fi
             TARGET="build"
@@ -159,14 +144,6 @@ while true; do
                 exit 1
             fi
             ;;
-        -p|--preset)
-            PRESET_FLAG="--preset=$2"
-            shift 2
-            ;;
-        --build-dir)
-            BUILD_DIR="$2"
-            shift 2
-            ;;
         --now)
             DELAY_BEFORE_PURGE=0
             shift 1
@@ -189,9 +166,9 @@ if [[ "$TARGET" == "none" ]]; then
 fi
 
 if [[ "$TARGET" == "clean" || "$TARGET" == "rebuild" ]]; then
-    clean_build
+    clean
 fi
 
 if [[ "$TARGET" == "build" || "$TARGET" == "rebuild" ]]; then
-    build
+    build_colcon
 fi
